In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import *

In [2]:
print("Pi = " + str(pi))
print("The golden ratio = " + str(golden))
print("The speed of light = " + str(c))
print("The Planck constant = " + str(h))
print("The standard acceleration of gravity = " + str(g))
print("The Universal constant of gravity = " + str(G))

Pi = 3.141592653589793
The golden ratio = 1.618033988749895
The speed of light = 299792458.0
The Planck constant = 6.62606957e-34
The standard acceleration of gravity = 9.80665
The Universal constant of gravity = 6.67384e-11


In [2]:
import numpy as np
from scipy import linalg
a = np.array([[1, 4], [9, 16]])
b = linalg.inv(a)
print(b)

[[-0.8   0.2 ]
 [ 0.45 -0.05]]


In [7]:
a = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])
from scipy import linalg
x = linalg.solve(a, b)
print(x)
print(np.dot(a, x))

[ 2. -2.  9.]
[ 2.  4. -1.]


In [8]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(linalg.det(a))

0.0


In [10]:
a = np.arange(16).reshape((4, 4))
print(linalg.norm(a))
print(linalg.norm(a, np.inf))
print(linalg.norm(a, 1))
print(linalg.norm(a, -1))

35.2136337233
54
36
24


In [4]:
from numpy import random
from scipy import linalg
a = random.randn(3, 3)
q, r = linalg.qr(a)
print(a)
print(q)
print(r)

[[-0.14393358 -2.17574812  0.44271419]
 [-0.22635436  0.52711805  0.46305456]
 [ 0.40644007  0.03541494  0.77268022]]
[[-0.29556539  0.93247789  0.2076682 ]
 [-0.4648152  -0.33028381  0.82149829]
 [ 0.83461843  0.14627912  0.53105036]]
[[ 0.4869771   0.42762132  0.29880736]
 [ 0.         -2.19775511  0.37290876]
 [-0.         -0.          0.8826683 ]]


In [5]:
r, q = linalg.rq(a)
print(r)
print(q)

[[-1.63450097  1.49101808 -0.23635624]
 [-0.         -0.66145553 -0.32555466]
 [ 0.          0.         -0.87377484]]
[[ 0.67633136  0.62824668 -0.38455428]
 [ 0.57114571 -0.77695775 -0.26481924]
 [-0.46515424 -0.04053097 -0.88430129]]


In [6]:
from scipy import integrate
f1 = lambda x: x**4
print(integrate.quad(f1, 0, 3))

(48.599999999999994, 5.39568389967826e-13)


In [8]:
import numpy as np
f2 = lambda x: np.exp(-x)
print(integrate.quad(f2, 0, np.inf))

(1.0000000000000002, 5.842606742906004e-11)


In [9]:
print(integrate.trapz([1, 2, 3, 4, 5]))

12.0


In [14]:
import matplotlib.pyplot as plt
x = np.linspace(-2, 2, num=30)
y = x
y_int = integrate.cumtrapz(y, x, initial=0)
plt.plot(x, y_int, 'ro', x, y[0] + 0.5 * x**2, 'b-')
plt.show()

In [21]:
from scipy import interpolate
x = np.arange(0, 15)
y = np.exp(x/3.0)
f = interpolate.interp1d(x, y)
xnew = np.arange(0, 14, 0.1)
ynew = f(xnew)
plt.plot(x, y, 'o', xnew, ynew, '-')
plt.show()

In [22]:
x = np.arange(-5.01, 5.01, 0.25)
y = np.arange(-5.01, 5.01, 0.25)
xx, yy = np.meshgrid(x, y)
z = np.sin(xx**3 + yy**3)
f = interpolate.interp2d(x, y, z, kind='cubic')
xnew = np.arange(-5.01, 5.01, 1e-2)
ynew = np.arange(-5.01, 5.01, 1e-2)
znew = f(xnew, ynew)
plt.plot(x, z[0, :], 'ro-', xnew, znew[0, :], 'b-')
plt.show()

In [27]:
from scipy.interpolate import splev, splrep
x = np.linspace(-10, 10, 50)
y = np.sinh(x)
spl = splrep(x, y)
x2 = np.linspace(-10, 10, 50)
y2 = splev(x2, spl)
plt.plot(x, y, 'o', x2, y2)
plt.show()

In [31]:
from scipy.interpolate import splprep
theta = np.linspace(0, 2*np.pi, 80)
r = 0.5 + np.cosh(theta)
x = r * np.cos(theta)
y = r * np.sin(theta)
tck, u = splprep([x, y], s=0)
new_points = splev(u, tck)
plt.plot(x, y, 'ro')
plt.plot(new_points[0], new_points[1], 'r-')
plt.show()